### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by webanck** [VCityTeam/DatAgoraWebSite#7]
I am currently getting a 404 error on the website : https://projet.liris.cnrs.fr/vcity/DatAgora/
@EricBoix or @ggesquiere can you check the hosting server status? If I recall correctly, I don't have any access to this server.

**Comment by EricBoix** [comment]
The site automagically broke "up"...

**Comment by ggesquiere** [comment]
@EricBoix , did you made an action or is it really automatic ? 
Thks

**Comment by EricBoix** [comment]
@ggesquiere As far as I can remember, the problem had two facets:
 * at the time you tried it they were some technical interventions on the LIRIS laboratory website (I'm not sure that the project directories were properly served), that prevented the resulting website from working.
 * with the new "technology" the laboratory website is using, there seems to be a delay (of undocumented length) between the update of a project directory and its publication (availability through an http access).
 
 So after that we (with @webanck ) manually checked that the deployment was correct (that is that the runner had indeed pushed the generated website to the laboratory project host), which took quite some time, the web-site eventually started to work (without any known side-effect of our inquiries on the "auto-magic" reparation) 😃

**Comment by webanck** [comment]
And it is down again !

**Comment by EricBoix** [comment]
The files corresponding to https://projet.liris.cnrs.fr/vcity/DatAgora/ are just NOT there:
```bash
$ ssh connect ls -al /home-projets/vcity/public_html/DatAgora
   connect.liris.cnrs.fr Debian GNU/Linux
   ls: cannot access '/home-projets/vcity/public_html/DatAgora': No such file or directory
```

It looks like [your last commit](https://github.com/VCityTeam/DatAgoraWebSite/commit/b06e08ae98be3e07949ea01cf588254bb661cd20) (where you replaced the link checker)  triggered a CI that [did properly deploy the resulting DatAgora WebSite](https://app.travis-ci.com/github/VCityTeam/DatAgoraWebSite/builds/231939090#L554) (maybe we could make sure by adding a `-v` verbose flag to the `scp`?).
Otherwise the [link checker on the deployment would have failed](https://app.travis-ci.com/github/VCityTeam/DatAgoraWebSite/builds/231939090#L570) without being able to inspect the deployed site.

Something fishy here. Yet one thing seems for sure: the inability to access the DatAgora corporate website
does not seem due to the LIRIS website hosting service. One can tell because [VCity website]( https://projet.liris.cnrs.fr/vcity/) is up and well...

**Comment by EricBoix** [comment]
As of today, the https://projet.liris.cnrs.fr/vcity/DatAgora/ site is operational again.
Closing.

**Comment by webanck** [comment]
And it's down again.

**Comment by webanck** [comment]
Ok, the site gets broken every time the `VCity` main website is redeployed. Indeed, during the deployment, the main website is rebuilt from scratch, but not the subdirectory containing the DatAgora website.

First solution: edit the deployment script of the VCity main website to avoid wiping the DatAgora subdirectory.
Second solution: edit the deployment script of the VCity main website to rebuild the DatAgora subdirectory from scratch too.

As the two websites are split between GitLab and GitHub, I would recommend the first solution, avoiding process duplication between GitLab/VCity and GitHub/DatAgora.

**Comment by EricBoix** [comment]
MR submitted by @webanck on Gitlab repository was merged
and deployment realized again. Alas the DatAgora website had
been previously trashed (because of this issue).

@webanck Could you please re-deploy the DatAgora website ?

**Comment by webanck** [comment]
Yes, I just redeployed the DatAgora site with success.

@EricBoix Now, to check if the proposed tweak really keeps the DatAgora site alive, can you redeploy the VCity site?

**Comment by EricBoix** [comment]
The Vcity main website deployment script now cleanly sets aside the DatAgora website prior to updating.
Closing again (hopefully for the last time).
